export const industry1Data = [
    { text: "未指定", value: 0, selected: true },
    { text: "机械设备", value: 1 },
    { text: "软件游戏", value: 2 },
    { text: "教育培训", value: 3 },
    { text: "招商加盟", value: 4 },
    { text: "商务服务", value: 5 },
    { text: "装修装饰", value: 6 },
    { text: "生活用品", value: 7 },
    { text: "生活服务", value: 8 },
    { text: "交通类", value: 9 },
    { text: "电子电工", value: 10 },
    { text: "家用电器", value: 11 },
    { text: "农林牧渔", value: 12 },
    { text: "旅游及票务", value: 13 },
    { text: "服装鞋帽", value: 14 },
    { text: "休闲娱乐", value: 15 },
    { text: "安全安保", value: 16 },
    { text: "食品餐饮", value: 17 },
    { text: "节能环保", value: 18 },
    { text: "金融服务", value: 19 },
    { text: "IT产品", value: 20 },
    { text: "化妆品", value: 21 },
    { text: "房地产", value: 22 },
    { text: "通信服务", value: 23 },
    { text: "办公文教", value: 24 },
    { text: "图书音像", value: 25 },
    { text: "孕婴用品", value: 26 },
    { text: "铃声短信", value: 27 },
    { text: "彩票", value: 28 },
    { text: "电子商务", value: 29 },
    { text: "社交", value: 30 },
    { text: "招聘", value: 31 },
    { text: "资讯", value: 32 },
    { text: "分类信息", value: 33 },
    { text: "其他", value: 34 },
];
export const industry2Data = {
    0: [
        { text: "未指定", value: 0 },
    ],
    1: [
        { text: "未指定", value: 0 },
        { text: "通用机械设备", value: 1 },
        { text: "金属材料", value: 2 },
        { text: "化工机械", value: 3 },
        { text: "工程机械", value: 4 },
        { text: "五金机械", value: 5 },
        { text: "通用零配件", value: 6 },
        { text: "机床设备", value: 7 },
        { text: "通风设备", value: 8 },
        { text: "其他", value: 9 },
        { text: "模具", value: 10 },
        { text: "勘探机械", value: 11 },
        { text: "食品机械", value: 12 },
        { text: "橡塑设备", value: 13 },
        { text: "清洁设备", value: 14 },
        { text: "包装机械", value: 15 },
        { text: "物流设备", value: 16 },
        { text: "农林机械", value: 17 },
        { text: "商业设备", value: 18 },
        { text: "纺织机械", value: 19 },
        { text: "冶金机械", value: 20 },
        { text: "磨具", value: 21 },
        { text: "木工机械", value: 22 },
        { text: "造纸设备", value: 23 },
        { text: "医疗机械", value: 24 },
    ],
    2: [
        { text: "未指定", value: 0 },
        { text: "软件", value: 1 },
        { text: "游戏-客户端", value: 2 },
        { text: "游戏-网页", value: 3 },
        { text: "游戏-手游", value: 4 },
        { text: "网络小游戏", value: 5 },
        { text: "其他", value: 6 },
    ],
    3: [
        { text: "未指定", value: 0 },
        { text: "职业教育", value: 1 },
        { text: "高教自考", value: 2 },
        { text: "IT培训", value: 3 },
        { text: "语言培训", value: 4 },
        { text: "其他", value: 5 },
        { text: "家教和拓展", value: 6 },
        { text: "休闲培训", value: 7 },
        { text: "留学出国", value: 8 },
        { text: "基础教育", value: 9 },
        { text: "网络教育（网校）", value: 10 },
    ],
    4: [
        { text: "未指定", value: 0 },
        { text: "餐饮服务", value: 1 },
        { text: "家居建材", value: 2 },
        { text: "服装鞋帽", value: 3 },
        { text: "保健品", value: 4 },
        { text: "其他", value: 5 },
        { text: "饰品礼品", value: 6 },
        { text: "生活用品", value: 7 },
        { text: "机械电子", value: 8 },
        { text: "干洗加盟", value: 9 },
        { text: "教育培训", value: 10 },
        { text: "娱乐休闲", value: 11 },
        { text: "美容化妆", value: 12 },
    ],
    5: [
        { text: "未指定", value: 0 },
        { text: "出国", value: 1 },
        { text: "咨询策划", value: 2 },
        { text: "代理", value: 3 },
        { text: "其他", value: 4 },
        { text: "调查", value: 5 },
        { text: "设计", value: 6 },
        { text: "招聘", value: 7 },
        { text: "会计审计", value: 8 },
        { text: "公关", value: 9 },
        { text: "信息服务", value: 10 },
        { text: "法律服务", value: 11 },
        { text: "翻译", value: 12 },
        { text: "拍卖", value: 13 },
        { text: "配音", value: 14 },
    ],
    6: [
        { text: "未指定", value: 0 },
        { text: "建筑装修材料", value: 1 },
        { text: "建筑工程", value: 2 },
        { text: "装修服务", value: 3 },
        { text: "其他", value: 4 },
        { text: "家装材料", value: 5 },
        { text: "家装设计", value: 6 },
        { text: "家具及卖场", value: 7 },
    ],
    7: [
        { text: "未指定", value: 0 },
        { text: "家具", value: 1 },
        { text: "日常用品", value: 2 },
        { text: "眼镜钟表", value: 3 },
        { text: "其他", value: 4 },
        { text: "厨具餐具", value: 5 },
        { text: "箱包皮具", value: 6 },
        { text: "礼品", value: 7 },
        { text: "工艺品", value: 8 },
        { text: "饰品", value: 9 },
    ],
    8: [
        { text: "未指定", value: 0 },
        { text: "婚庆摄影", value: 1 },
        { text: "其他", value: 2 },
        { text: "搬家", value: 3 },
        { text: "保洁", value: 4 },
        { text: "征婚交友", value: 5 },
        { text: "保姆家政", value: 6 },
        { text: "虫害控制", value: 7 },
        { text: "办证刻章", value: 8 },
    ],
    9: [
        { text: "未指定", value: 0 },
        { text: "物流", value: 1 },
        { text: "租车", value: 2 },
        { text: "其他", value: 3 },
        { text: "汽车厂商", value: 4 },
        { text: "汽车经销商", value: 5 },
        { text: "航空公司", value: 6 },
        { text: "汽配及服务", value: 7 },
        { text: "二手车", value: 8 },
        { text: "共享单车", value: 9 },
        { text: "违章", value: 10 },
        { text: "加油卡", value: 11 },
    ],
    10: [
        { text: "未指定", value: 0 },
        { text: "仪器仪表", value: 1 },
        { text: "电源设备", value: 2 },
        { text: "电线电缆", value: 3 },
        { text: "电工器材", value: 4 },
        { text: "电子元件", value: 5 },
        { text: "电机设备", value: 6 },
        { text: "照明设备", value: 7 },
        { text: "其他", value: 8 }
    ],
    11: [
        { text: "未指定", value: 0 },
        { text: "手机数码", value: 1 },
        { text: "冷暖", value: 2 },
        { text: "音响", value: 3 },
        { text: "卫浴", value: 4 },
        { text: "其他", value: 5 },
        { text: "厨用", value: 6 },
        { text: "影视", value: 7 },
        { text: "家用电器", value: 8 },
        { text: "数码影音", value: 9 },
    ],
    12: [
        { text: "未指定", value: 0 },
        { text: "种植", value: 1 },
        { text: "养殖", value: 2 },
        { text: "园林景观", value: 3 },
        { text: "其他", value: 4 },
        { text: "化肥", value: 5 },
        { text: "农药", value: 6 },
        { text: "兽医兽药", value: 7 }
    ],
    13: [
        { text: "未指定", value: 0 },
        { text: "旅游", value: 1 },
        { text: "宾馆", value: 2 },
        { text: "交通票务", value: 3 },
        { text: "其他", value: 4 },
        { text: "文体票务", value: 5 },
    ],
    14: [
        { text: "未指定", value: 0 },
        { text: "服饰-运动", value: 1 },
        { text: "服饰-内衣", value: 2 },
        { text: "服饰-童装", value: 3 },
        { text: "服饰-职业休闲", value: 4 },
        { text: "服饰-其他", value: 5 },
        { text: "纺织辅料", value: 6 },
        { text: "鞋帽", value: 7 },
        { text: "皮革", value: 8 },
    ],
    15: [
        { text: "未指定", value: 0 },
        { text: "体育器械", value: 1 },
        { text: "玩具模型", value: 2 },
        { text: "其他", value: 3 },
        { text: "乐器", value: 4 },
        { text: "星座占卜", value: 5 },
        { text: "宠物", value: 6 },
        { text: "旅行社", value: 7 },
        { text: "旅游局", value: 8 },
        { text: "酒店", value: 9 },
    ],
    16: [
        { text: "未指定", value: 0 },
        { text: "交通消防", value: 1 },
        { text: "防盗报警", value: 2 },
        { text: "保安安保", value: 3 },
        { text: "门禁考勤", value: 4 },
        { text: "其他", value: 5 },
        { text: "警用装备", value: 6 },
    ],
    17: [
        { text: "未指定", value: 0 },
        { text: "食品", value: 1 },
        { text: "饮料", value: 2 },
        { text: "食用油调料", value: 3 },
        { text: "其他", value: 4 },
        { text: "餐馆", value: 5 },
        { text: "饮食原料", value: 6 },
        { text: "烟草", value: 7 },
        { text: "酒类", value: 8 },
        { text: "零售", value: 9 },
        { text: "商业", value: 10 },
    ],
    18: [
        { text: "未指定", value: 0 },
        { text: "污染处理", value: 1 },
        { text: "废旧回收", value: 2 },
        { text: "节能", value: 3 },
        { text: "其他", value: 4 },
    ],
    19: [
        { text: "未指定", value: 0 },
        { text: "保险", value: 1 },
        { text: "股票基金", value: 2 },
        { text: "银行产品", value: 3 },
        { text: "其他", value: 4 },
        { text: "期货外汇", value: 5 },
        { text: "发票", value: 6 },
        { text: "理财", value: 7 },
        { text: "信用卡", value: 8 },
        { text: "贷款", value: 9 },
    ],
    20: [
        { text: "未指定", value: 0 },
        { text: "电脑厂商", value: 1 },
        { text: "外设", value: 2 },
        { text: "耗材", value: 3 },
        { text: "配件", value: 4 },
        { text: "网络设备", value: 5 },
        { text: "软件", value: 6 },
        { text: "硬件", value: 7 },
        { text: "其他", value: 8 },
    ],
    21: [
        { text: "未指定", value: 0 },
        { text: "化妆品", value: 1 },
        { text: "珠宝首饰", value: 2 },
        { text: "奢侈品", value: 3 },
        { text: "其他", value: 4 },
        { text: "护肤品", value: 5 },
    ],
    22: [
        { text: "未指定", value: 0 },
        { text: "房产买卖", value: 1 },
        { text: "房屋出租", value: 3 },
        { text: "开发商", value: 4 },
        { text: "中介", value: 5 },
        { text: "其他", value: 2 },
    ],
    23: [
        { text: "未指定", value: 0 },
        { text: "通信设备", value: 1 },
        { text: "通信终端", value: 2 },
        { text: "设备厂商", value: 3 },
        { text: "运营商", value: 4 },
        { text: "广播电视服务", value: 5 },
        { text: "其他", value: 6 },
    ],
    24: [
        { text: "未指定", value: 0 },
        { text: "办公设备", value: 1 },
        { text: "教学设备", value: 2 },
        { text: "其他", value: 3 },
        { text: "文具", value: 4 },
    ],
    25: [
        { text: "未指定", value: 0 },
        { text: "图书", value: 1 },
        { text: "其他", value: 2 },
        { text: "投稿发行", value: 3 },
        { text: "音像", value: 4 },
        { text: "报纸杂志", value: 5 },
        { text: "印刷", value: 6 },
        { text: "包装", value: 7 },
    ],
    26: [
        { text: "未指定", value: 0 },
        { text: "孕婴用品", value: 1 },
    ],
    27: [
        { text: "未指定", value: 0 },
        { text: "短信彩信", value: 2 },
        { text: "铃声图片", value: 3 },
        { text: "其他", value: 4 },
    ],
    28: [
        { text: "未指定", value: 0 },
        { text: "福彩", value: 1 },
        { text: "体彩", value: 2 },
        { text: "其他", value: 3 },
    ],
    29: [
        { text: "未指定", value: 0 },
        { text: "垂直B2C", value: 1 },
        { text: "综合B2C", value: 2 },
        { text: "B2B", value: 3 },
        { text: "团购", value: 4 },
        { text: "其他", value: 5 },
        { text: "商城", value: 6 },
        { text: "导购聚合页", value: 7 },
    ],
    30: [
        { text: "未指定", value: 0 },
        { text: "婚恋", value: 1 },
        { text: "其他", value: 2 },
        { text: "微博", value: 3 },
        { text: "休闲", value: 4 },
        { text: "论坛", value: 5 },
    ],
    31: [
        { text: "未指定", value: 0 },
        { text: "招聘", value: 1 },
    ],
    32: [
        { text: "未指定", value: 0 },
        { text: "资讯-汽车", value: 2 },
        { text: "资讯-其他", value: 3 },
        { text: "资讯-房产", value: 4 },
        { text: "资讯-视频网站", value: 5 },
        { text: "资讯-军事", value: 6 },
        { text: "资讯-门户", value: 7 },
    ],
    33: [
        { text: "未指定", value: 0 },
        { text: "分类信息", value: 1 }
    ],
    34: [
        { text: "未指定", value: 0 },
        { text: "其他", value: 1 }
    ],
}